version: "3.7"

services:
    app:
        build:
            args:
                user: user
                uid: 1000
            context: ./
            dockerfile: ./php/Dockerfile
        image: laravel-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ../:/var/www
        networks:
            - test-app

    #Nginx Service
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ../:/var/www
            - ./nginx:/etc/nginx/conf.d/
        networks:
            - test-app

    #Mysl Service
    db:
        image: postgres:alpine
        restart: always
        environment:
            POSTGRES_USER: tester
            POSTGRES_PASSWORD: 123456
            POSTGRES_DB: test
        ports:
            - "5432:5432"
        networks:
            - test-app


    adminer:
        image: adminer
        restart: always
        ports:
            - "7788:8080"
        depends_on:
            - db
        networks:
            - test-app

networks:
    test-app:
        driver: bridge
